# Change these first
owner: fideo # Your GitHub organization or username, where this repository lives
repo: statusSites # The name of this repository

sites:
  - name: FedericoMazzei
    url: https://www.federicomazzei.com.ar
    icon: https://www.federicomazzei.com.ar/favicon.png
  - name: MetalurgicaMiele
    url: https://www.metalurgicamiele.com.ar
    icon: https://www.metalurgicamiele.com.ar/favicon.ico
  - name: Distribuidora RN
    url: https://www.distribuidorarn.com.ar
    icon: https://www.distribuidorarn.com.ar/wp-content/uploads/2022/01/cropped-cropped-cropped-LOGO_BW-32x32.png
  - name: Argenchemical SRL
    url: https://www.argenchemical.com.ar
    icon: https://www.argenchemical.com.ar/favicon.ico
  - name: ClanSamurai
    url: https://www.clansamuraiargentino.com.ar
    icon: https://www.clansamuraiargentino.com.ar/imagenes/Sasa_Rindo.svg
  - name: PartsSistemas
    url: https://partssistemas.com.ar
    icon: https://partssistemas.com.ar/wp-content/uploads/2024/09/icon_partssistemas.png
  - name: ItalGroup SA
    url: https://italgroupsa.com.ar
    icon: https://italgroupsa.com.ar/wp-content/uploads/2024/06/icono-logo-Italgroup-100x100.webp
  - name: IgTrailers
    url: https://igtrailers.com.ar
    icon: https://igtrailers.com.ar/wp-content/uploads/2016/09/cropped-ico-150x150.png

assignees:
  - fideo

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /statusSites
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Sitios Fideo
  introTitle: "**Status Sitios Fideo** es un página que muestra los estados de los sitios listados, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  introMessage: Esto puede configurarse usando [GitHub repository](https://github.com/upptime/upptime). No se necesita server, solo GitHub Actions, Issues y Pages.
  navbar:
    - title: Status Sitios Fideo
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
